### ISSUE TITLE
Support multi-GPU multi-node mode (MGMN)

### ISSUE THREAD

**Issue by amontoison** [exanauts/CUDSS.jl#59]
https://github.com/NVIDIA/CUDALibrarySamples/blob/master/cuDSS/simple_mgmn_mode/simple_mgmn_mode.cpp
cc @frapac @sshin23

**Comment by sloisel** [comment]
I already use CUDSS_jll.jl directly and MGMN in [LinearAlgebraMPI.jl](https://github.com/sloisel/LinearAlgebraMPI.jl/blob/main/ext/LinearAlgebraMPICUDAExt.jl). I've had to bypass CUDSS.jl and NCCL.jl in favor of CUDSS_jll.jl and NCCL_jll.jl because of essentially the same bug, which is the same bug as in [MUMPS](https://github.com/JuliaSmoothOptimizers/MUMPS.jl/issues/183). So you're using Julia finalizers to cleanup CUDSS resources, see [this](https://github.com/search?q=repo%3Aexanauts%2FCUDSS.jl%20finalizer&type=code). When you have more than 1 rank, each rank will execute finalizers in some order, generally not the same order, and also at nondeterministic times. It turns out that CUDSS cleanup is a collective operation so every time that I run CUDSS.jl on 2 nodes on the Heriot-Watt University DMOG cluster, CUDSS.jl hangs because of desynchronization.

The solution is to not use Julia finalizers in CUDSS.jl. You should treat it like open() and close(), user is responsible for calling close(), with the plot twist that close() is a collective operation.
